- name: Provision server
  hosts: all
  become: yes
  
  roles:
    - common
    - docker
    - users
    - project

  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted